data_dir: data/sample
image_dir: data/raw/images

model_dir: outputs/saved_models

latest_step: 0

use_gpu: true #true
epochs: 10 #300
batch_size: 24  #16
lr: 0.00001
embed_dim: 768

blip2_model_id: Salesforce/blip2-flan-t5-xl

lora_rank: 8
lora_alpha: 16
lora_dropout: 0.1

scheduler: cosine_with_warmup
weight_decay: 0.01
warmup_steps: 50

recall_ks: [1, 10, 50]
